Contracts first version
lfj-gg/plague-game-contracts pull request #1
Opened 2022-10-18 13:40 UTC by Mathieu-Be

### Contract for the plague game

_**First of all you should read the game specs that can be found [here](https://www.notion.so/traderjoexyz/Plague-Game-a95cfe84473142639487f5f0684bf210).**_

The basic flow of the game is:
1. `startEpoch` to use the random numbers to make doctors sick
2. Play the round and cure doctors
3. `endEpoch` to make the remaining infected doctors `dead` and then ask for VRF
4. VRF callback that allows the next round to start

A large amount of doctors needs to be randomly infected, so to reduce the cost of VRF I'm using each random number 8 times. It would be even smoother if the VRF callback could call `startEpoch` but the callback is limited to 2.5 million `wei` of gas.

Picking a random item in an array is pretty heavy in gas so I made these choices to make the game flow smooth:
- An array with the healthy doctors is initialized before the beginning of the game (that's very expensive and needs to be executed in a few steps)
- Doctors are removed from the array when infected at the start of the round. This is heavy in gas too but with the expected size of the collection, it doesn't go higher than 5 million `wei` at worst during the tests, which seems safe but I'm waiting for a bug fix on Foundry to make sure it doesn't go higher during the fuzzing tests.
- Doctors are put in the array again when cured

I also added a Github workflow to run foundry tests on PRs, hopefully it will work

2022-10-20 06:36 UTC, simsk87 commented on src/PlagueGame.sol
> +        if (healthyDoctors.length() <= 10 || currentEpoch == 12) {
should this check use `playerNumberToEndGame` and `totalEpochNumber`?

2022-10-25 20:53 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    event DoctorsInfectedThisEpoch(uint256 indexed epoch, uint256 deadDoctors);
```suggestion
    event DoctorsInfectedThisEpoch(uint256 indexed epoch, uint256 infectedDoctors);
```

2022-10-25 21:04 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    bool public gameStarted;
```suggestion
    bool public isGameStarted;
```

2022-10-25 21:08 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    }
Are we sure we want to burn the nft or should we just blacklist it? 

I'm thinking maybe people will still want to speculate or something?

2022-10-25 22:12 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    }
or maybe we could mint them an empty potion automatically after burning?

2022-10-26 08:53 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    mapping(uint256 => uint256) public infectedDoctorsPerEpoch;
could we have another mapping `deadDoctorsPerEpoch` ?
`mapping(uint256 => uint256) public deadDoctorsPerEpoch`

This is for the frontend. 

We could also read from past events but I think it's easier if we have it in a mapping

2022-10-26 08:57 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    mapping(uint256 => uint256) public infectedDoctorsPerEpoch;
Yes that shouldn't be too much gas expensive, I'll add it

2022-10-27 21:03 UTC, 0x0Louis requested changes

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +error FundsTransferFailed();
Right now, if someone imports the interface, it will not be able to get errors.
Add errors to the interface or in a separate file that you import in the interface.

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    /// @notice Percentage of doctors that will  be infected each epoch
2 spaces `will  be`

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    /// @dev Stores if an epoch has started
Should mention ended, not started

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    /// @notice Stores the number of doctors infected each epoch. This is purely for the front-end
`Stores the number of INFECTED doctors AT each epoch`

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    /// @notice Stores the number of dead doctors each epoch. This is purely for the front-end
``Stores the number of dead doctors AT each epoch``

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    /// @notice True is the game is over
`Whether the game is over (true), or not (false)`

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    /// @notice True is the game started
Whether the game is started (true), or not (false)

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256[] memory _infectionPercentagePerEpoch,
`uint256[] calldata _infectionPercentagePerEpoch,`

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint32 wordsNumber = uint32(infectedDoctors / 8 + 1);
Should be `infectedDoctors == 0 ? 0 : uint32((infectedDoctors - 1) / 8 + 1);`

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    EnumerableSet.UintSet private healthyDoctors;
Instead of having a set of `1_000` doctors (so >2_000 slots) and `1_000` slot for their status, I would be in favour of doing the big brain way:

doctor status:
As it uses enums,
- Dead is 0
- Healthy is 1
- Infected is 2
And that one doctor can only be one of those statuses at a time, I'm in favor of using 2 bits for each doctor. That way, one slot can store 128 doctors, so with only 8 slots that cover the entire collections (use a for loop to create the array with a length of `(doctorNumber - 1) / 128 + 1`.
To initialize it, you just need to set every index to `0x5555555555555555555555555555555555555555555555555555555555555555`, and for the last index it should be set to `0x5555555555555555555555555555555555555555555555555555555555555555 >> (2*(128 - (doctorNumber % 128)))`
A function to get the state of a specific doctor would need to be added, that would be something like:
- `index = id / 128`
- `bit = 2* (id % 128)`
and return `(doctorState[index] >> bit) & 0x3`

About the healthy doctors set, as there are only 1_000 doctors, you can use one slot for 25 doctors (1000 fits in uint10, and `256 // 10 = 25`). To remove a doctor, you take the last id and put it in at the bit index, and remove the last index from the list. Reducing the array itself is not needed as long as you keep the number of healthy doctors as a value as well.
When a doctor is cured, it should be added at the end of the list.

The trick is that we don't need to store the index of the doctor is the doctorStatus array as it is deterministic and we can calculate it.

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +            slicedRadomNumber = uint32(_randomNumber >> 32 * _offset);
To query less numbers I would do something like:
```
slicedRadomNumber = _randomNumber % nbHealthyDoctor;
_randomNumber /= nbHealthyDoctor;
```
And reusing this _randomNumber for the next step.
This way with one uint256, you can do as much as 25 random numbers.
And when `_randomNumber < nbHealthyDoctor`, use a new random

2022-10-27 21:03 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        if (_requestId != epochVRFRequest[currentEpoch + 1]) {
Cache `epochVRFRequest[currentEpoch + 1]`

2022-10-28 13:00 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    EnumerableSet.UintSet private healthyDoctors;
I'll try this on another branch after merging the first PR. I have mixed feelings, it's cool but is it really worth the time to add so much complexity, just to save 3 or 4 AVAX ?

2022-10-29 08:18 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +        uint256[] memory _infectionPercentagePerEpoch,
You can't use `calldata` in the constructor

2022-10-29 08:53 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +            slicedRadomNumber = uint32(_randomNumber >> 32 * _offset);
I overcomplicated things, a single random number is sufficient actually. I changed the way it works in commit [b5f6830](https://github.com/traderjoe-xyz/plague-game-contracts/pull/1/commits/b5f683001ba85f8e44730d63d85f528f1c67576d)

2022-10-29 22:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +            slicedRadomNumber = uint32(_randomNumber >> 32 * _offset);
I kind of wanted to suggest what you did in this commit, but it increases gas cost compared to splitting then keccak, but not a lot so w/e

2022-10-29 23:43 UTC, 0x0Louis approved these changes

2022-10-29 23:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256[] memory _infectionPercentagePerEpoch,
Oh indeed mb

2022-10-29 23:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256 toMakeSick = healthyDoctorsNumber * _getinfectionRate(currentEpochCached) / BASIS_POINT;
This should probably round up as the game can be infinite because of the rounding down.
(for example, the game ends when 10 doctors are sick, 11 doctors left, 9% infection rate -> `toMakeSick = 0` and the game can't end)

2022-10-29 23:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    function endEpoch() external override gameOn {
Could run out of gas if the infection rate is high at the start of the game. Either use pagination or be careful with the infection rate and test it before

2022-10-29 23:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    }
Should check that `(block.timestamp < epochStartTime + epochDuration)` or you can cure your doctor even after the epoch should have ended, and an epoch can last forever.

2022-10-29 23:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        epochVRFRequest[currentEpoch + 1] = vrfCoordinator.requestRandomWords(keyHash, subscriptionId, 3, maxGas, 1);
Cache `currentEpoch`

2022-10-29 23:43 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        emit RandomWordsFulfilled(currentEpoch + 1, _requestId);
Cache `currentEpoch + 1`

2022-10-30 01:51 UTC, 0xmurloc commented
This might be stupid question but why not start w/ empty array and add dead doctors to the list? 

> Picking a random item in an array is pretty heavy in gas so I made these choices to make the game flow smooth:
> 
> * An array with the healthy doctors is initialized before the beginning of the game (that's very expensive and needs to be executed in a few steps)
> * Doctors are removed from the array when infected at the start of the round. This is heavy in gas too but with the expected size of the collection, it doesn't go higher than 5 million `wei` at worst during the tests, which seems safe but I'm waiting for a bug fix on Foundry to make sure it doesn't go higher during the fuzzing tests.
> * Doctors are put in the array again when cured
>

2022-10-31 08:37 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +            slicedRadomNumber = uint32(_randomNumber >> 32 * _offset);
Yeah we would need to compare the extra gas cost vs LINK required to get more random numbers

2022-10-31 08:39 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    }
You can't have doctors infected after the end of the epoch, they are either dead or alive.

2022-10-31 09:01 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    function endEpoch() external override gameOn {
`startEpoch` is actually heavier, but I'm testing with a slightly bigger collection than planned and it doesn't go over 5 million wei at most during the tests (foundry's `--gas-report` includes a part of the fuzzing tests in the report).

2022-10-31 09:15 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +        uint256 toMakeSick = healthyDoctorsNumber * _getinfectionRate(currentEpochCached) / BASIS_POINT;
On the other hand, rouding up could lead to infecting all the doctors and end up with no winners. I did this instead:
```
 if (toMakeSick == 0) {
    toMakeSick = 1;
}

if (toMakeSick == healthyDoctorsNumber) {
    toMakeSick -= 1;
}
```

2022-10-31 09:20 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    uint256 private immutable totalDefinedEpochNumber;
can you make this public so the frontend can read it please? @Mathieu-Be

2022-10-31 09:22 UTC, Mathieu-Be commented
> This might be stupid question but why not start w/ empty array and add dead doctors to the list?
> 
> > Picking a random item in an array is pretty heavy in gas so I made these choices to make the game flow smooth:
> > 
> > * An array with the healthy doctors is initialized before the beginning of the game (that's very expensive and needs to be executed in a few steps)
> > * Doctors are removed from the array when infected at the start of the round. This is heavy in gas too but with the expected size of the collection, it doesn't go higher than 5 million `wei` at worst during the tests, which seems safe but I'm waiting for a bug fix on Foundry to make sure it doesn't go higher during the fuzzing tests.
> > * Doctors are put in the array again when cured

I need it to select the random doctor to be infected. Without it I would need to loop on the whole collection each time to find the n-th doctor to infect and the gas costs would rise quickly (would be O(n<sup>2</sup>) on the collection size)

2022-10-31 09:26 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    uint256 private immutable totalDefinedEpochNumber;
Done 🫡

2022-10-31 09:28 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    uint256 private immutable totalDefinedEpochNumber;
Wait, what if I make `_getinfectionRate` public instead ? Would be even easier no ?

2022-10-31 12:29 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    uint256 private immutable totalDefinedEpochNumber;
I wanted to use it for this:
<img width="121" alt="Screenshot 2022-10-31 at 13 28 27" src="https://user-images.githubusercontent.com/52084503/199007800-2624b9c8-d0b3-4630-acb5-994eeaabe252.png">

-> currentEpoch / totalDefinedEpochNumber

2022-10-31 14:02 UTC, Max-3-7 commented on src/PlagueGame.sol
> +    }
yeah from my tests I noticed that if `endEpoch` hasn't been called yet, you can still drink potions even though the end time is reached (not sure if that's a big deal though)

2022-11-02 04:05 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256 toMakeSick = healthyDoctorsNumber * _getinfectionRate(currentEpochCached) / BASIS_POINT;
Sounds good

2022-11-02 04:06 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    }
That was my concern as well @Max-3-7. To me, it is as it doesn't enforce the end of the epoch

2022-11-02 04:10 UTC, 0x0Louis requested changes

2022-11-02 04:10 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256 toMakeSick = healthyDoctorsNumber * _getinfectionRate(currentEpochCached) / BASIS_POINT;
However, you need to ensure that `playerNumberToEndGame > 0` in the constructor then

2022-11-02 08:38 UTC, Mathieu-Be commented on src/PlagueGame.sol
> +    }
Ooh yeah I see, would be unfair if people can cure their doctors between the time the epoch has ended and the call to `endEpoch` indeed.

2022-11-02 11:54 UTC, 0x0Louis approved these changes

2022-11-02 13:49 UTC, merged