[WIP] Add Apothecary contract for brewing potions
lfj-gg/plague-game-contracts pull request #2
Opened 2022-11-10 03:12 UTC by JO-OLADEJI

`Apothecary` contract for brewing potions for plague doctors.

2022-11-10 13:47 UTC, 0x0Louis requested changes
Write tests, so much blunder that should be caught by tests

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +/// @notice Contract for alive plague doctors to attempt brew a potion at epocs
Change to
`Contract for alive plague doctors to attempt to brew a potion at each epoch.`

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +            vrfCoordinator.requestRandomWords(keyHash, subscriptionId, 3, maxGas, 1);
Remove magical numbers

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +    /// @notice Probability of a doctor getting a potion from chest. [1 - 100] typically
`Probability for a doctor to receive a potion when he tries to brew one. From 1 (1%) to 100 (100%)`

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +    /// @notice Timestamp of begining of latest (current) epoch
`Timestamp of the start of the latest (current) epoch`

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +    uint112 public constant EPOCH = 6 hours;
Change to `EPOCH_DURATION`

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +    /// @notice Token ID of plague doctor that called VRF for epoch
Change to `Token id of the plague doctor that called the VRF for the current epoch`

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +    /// @dev Cache plague doctor ID to avoid multiple tx for first brew in epoch
Change to `Cache the id of the plague doctor that called the VRF. It avoids calling the VRF multiple times`

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +        if (latestEpochTimestamp + EPOCH > block.timestamp) {
Wrong way, should be `latestEpochTimestamp + EPOCH < block.timestamp` (it could be `<=`, this depends on your implementation)

2022-11-10 13:47 UTC, 0x0Louis commented on src/Apothecary.sol
> +        hasNotBrewedInLatestEpoch(_doctorId)
Can be called multiple times during the 3 block that the VRF will wait

2022-11-17 15:36 UTC, Mathieu-Be requested changes

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +    /// @notice From 1 (1%) to 100 (100%)
This is the opposite actually: `x % 1` will always be 0, so you have 100% chances.

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +    uint8 private difficulty;
No need to use smaller variable types, you can use `uint256` everywhere

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +        }
We will need higher bounds on this. The goal is to distribute only a couple of potions per epoch, so I would say 1 chances out of 100k maximum to have some margin

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +    }
It is good practice to validate the `_requestId` (first argument of the function) on this. You need to be sure that the VRF coordinator is answering to the correct request.

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +            potions.safeTransferFrom(address(this), doctors.ownerOf(_doctorId), potionId);
You can use `safeTransfer` since you're transfering from the contract itself.

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +    function _getPotionIds(uint256 _count) private view returns (uint256[] memory) {
This function is only used to fetch one single potion, you could probably simplify

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +    function _getTotalBrewsCount(uint256 _doctorId) private view returns (uint256 doctorBrewsCount) {
This reads a ton of storage slots, are you sure it won't revert at some point ?

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +        for (uint256 i = 0; i < brewLogs.length;) {
You can cache `brewLogs.length`

2022-11-17 15:36 UTC, Mathieu-Be commented on test/Apothecary.t.sol
> +            vm.warp(block.timestamp + apothecary.EPOCH_DURATION() + 1);
You can use `skip(apothecary.EPOCH_DURATION() + 1)`, it's a bit more convenient

2022-11-17 15:36 UTC, Mathieu-Be commented on test/Apothecary.t.sol
> +        assertEq(apothecary.getBrewLogs(doctorA, MAX_EPOCH_ATTEMPTS).length, doctorABrewsCount);
It's a good practice to add messages to your assertions (you can put a string as the third input). This way when one of the assertion fails, you know which one it is

2022-11-17 15:36 UTC, Mathieu-Be commented on src/Apothecary.sol
> +            potionIds[i] = potions.tokenOfOwnerByIndex(address(this), i);
We will probably use a Launchpeg contract for the potions, and it doesn't support this function

2022-11-17 20:23 UTC, Mathieu-Be commented
Can you also add a `startTime` like I just added for the game contract ? Right now people can brew as soon as the doctor is alive, which will be true as soon as we initialize the game.

2022-11-17 23:46 UTC, JO-OLADEJI commented on src/Apothecary.sol
> +            potions.safeTransferFrom(address(this), doctors.ownerOf(_doctorId), potionId);
Didn't find `safeTransfer()` in the `ERC721` contract.

2022-11-17 23:57 UTC, JO-OLADEJI commented on src/Apothecary.sol
> +    function _getTotalBrewsCount(uint256 _doctorId) private view returns (uint256 doctorBrewsCount) {
Hmmmm.
Not sure. WDYT @0x0Louis ?

2022-11-18 03:05 UTC, JO-OLADEJI commented on src/Apothecary.sol
> +        hasNotBrewedInLatestEpoch(_doctorId)
Fixed.

2022-11-18 12:57 UTC, 0x0Louis commented on src/Apothecary.sol
> +    function _getTotalBrewsCount(uint256 _doctorId) private view returns (uint256 doctorBrewsCount) {
It will definitely revert after the 3809th potion as it costs 2100 gas to access a slot for the first time, and `8_000_000 / 2_100 = 3809.52`

2022-11-18 13:10 UTC, 0x0Louis commented on src/Apothecary.sol
> +    uint8 private difficulty;
That's actually wrong, solidity packs smaller type together and this will save gas as querying the same storage costs less.
However, mapping or dynamic arrays aren't packed together (it costs always less to use `mapping(uint256 => X)` than `mapping(uint96 => X)`)
E.g:
This uses 4 slots:
```solidity
address user0; // slot 0
address user1; // slot 1
uint256 val0; // slot 2
uint256 val1; // slot 3
```

This uses 3 slots:
```solidity
address user0; // slot 0
address user1; // slot 1 (first 20 bytes)
uint96 val0; // slot 1 (last 12 bytes)
uint96 val1; // slot 2
```

This uses 2 slots:
```solidity
address user0; // slot 0 (first 20 bytes)
uint96 val0; // slot 0 (last 12 bytes)
address user1; // slot 1 (first 20 bytes)
uint96 val1; // slot 1 (last 12 bytes)
```

2022-11-18 13:48 UTC, Mathieu-Be commented on src/Apothecary.sol
> +    uint8 private difficulty;
Yeah but if you pack your variables randomly that's probably gonna be slots that you read only once, and you will have to read + mask. And you have to be much more careful with overflows

2022-11-18 14:14 UTC, JO-OLADEJI commented on src/Apothecary.sol
> +    function _getTotalBrewsCount(uint256 _doctorId) private view returns (uint256 doctorBrewsCount) {
After the 3809th potion or after **3809 brew logs**??

2022-11-18 16:18 UTC, 0x0Louis requested changes

2022-11-18 16:18 UTC, 0x0Louis commented on src/Apothecary.sol
> +    function _getTotalBrewsCount(uint256 _doctorId) private view returns (uint256 doctorBrewsCount) {
After the `3809th brewLogs`, but it doesn't really matter, it will cost too much gas even if it didn't revert

2022-11-21 09:00 UTC, closed without merging