Gas optimizations
lfj-gg/plague-game-contracts pull request #3
Opened 2022-11-14 14:04 UTC by Mathieu-Be

Gas optimizations to allow running the game on big sized collections

- Removed the `EnumerableSet`
- Packed doctor statuses and healthy doctors IDs into uints
- Removed events on doctor infected and dead
- Replaced `deadDoctorsPerEpoch` by `curedDoctorsPerEpoch`

`startEpoch` is now paginated for extra safety, using an additional `computeInfectedDoctors` function. `endEpoch` is now very light.

2022-11-15 11:39 UTC, 0x0Louis requested changes

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
>          }
This only work because `10_000 % 16 = 0`, if for some reason we don't mint **all** the supply, this will add unminted doctors to the set

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256 newlastHealthyDoctorsSetItemUpdated = lastHealthyDoctorsSetItemUpdatedCached + _amount;
Rename this to something shorter, e.g: `currentLastDoctorInSet` and `lastDoctorIdToAdd`

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +
All private vars should start with an underscore

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +    uint256 private lastHealthyDoctorsSetItemUpdated;
Change to `_lastDoctorAdded`

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +            }
This can be simplified to:
```solidity
// constants
uint256 private constant _range = 0xf000e000d000c000b000a0009000800070006000500040003000200010000;
uint256 private constant _offset = 0x10001000100010001000100010001000100010001000100010001000100010;
```
```solidity
for (uint256 j = lastHealthyDoctorsSetItemUpdatedCached; j < newlastHealthyDoctorsSetItemUpdated; j++) {
     uint256 doctorIds = _range + _offset * j
     healthyDoctorsSet[j] = doctorIds;
}
```

to make it work with non total supply minted, you need to use a mask or double cast (`(doctorIds << bit) >> bit`) on the last id with `bit = 256 - (doctorNumber % 16) * 16`

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
>          }
Needs to be `newlastHealthyDoctorsSetItemUpdated  > (doctorNumber + 15) / 16` in case the total supply is not minted

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        if (doctorNumber > 10_000) {
It should also revert if `doctorNumber == 0` as it would break the end of the game, and would probably mean we used the wrong contract

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
>          }
Cache `infectedDoctorsPerEpoch[nextEpoch]`

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        uint256 computedInfectionsCached = computedInfections[nextEpoch];
This was already cached to `offset`, use the cached var

2022-11-15 11:39 UTC, 0x0Louis commented on src/PlagueGame.sol
> +        healthyDoctorsSet[healthyDoctorsNumber / 16] = lastDoctorSetItem;
Cache `healthyDoctorsNumber`

2022-11-15 14:06 UTC, Mathieu-Be commented on src/PlagueGame.sol
>          }
Yes but only ids below `doctorNumber` will be considered so I figured it would be easier to write them anyway.

2022-11-15 18:33 UTC, 0x0Louis commented on src/PlagueGame.sol
>          }
Can you add a test for this specific case? Even if I agree with you, always great to have a test to assert that

2022-11-17 01:03 UTC, 0x0Louis approved these changes

2022-11-17 08:44 UTC, merged