Make potions from dead doctors
lfj-gg/plague-game-contracts pull request #8
Opened 2022-11-24 15:46 UTC by Mathieu-Be

This changes the way potions are claimed and brewed.

**Claiming:** to be done using `claimFirstPotions` and an array of doctor IDs. Doctors can claim after the `claimStartTime`, and only once.

**Brewing:** to be done using `makePotions` and an array of doctor IDs. There must be a multiple of 5 doctors in the array and they need to be all dead. Epochs are synced with the game, and `requestVRFforCurrentEpoch` needs to be called first (once per epoch).

2022-11-24 17:52 UTC, 0x0Louis requested changes

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
> +    function claimPotions(uint256[] calldata _doctorIDs) external override {
Rename to `claimInitialPotions` or `claimFirstPotions` to make it clearer

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
> +        ++totalBrewsCount;
This should be `totalBrewsCount  += doctorIDsLength`

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
>      }
This shouldn't set the previous epochs, even tho it doesn't change anything it would be too weird

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
> +    function setClaimStartTime(uint256 _startTime) external override onlyOwner {
Should emit an event

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
> +    function setDifficulty(uint256[] calldata difficultyPerEpoch_) external override onlyOwner {
Should emit an event

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
> +        _difficultyPerEpoch = difficultyPerEpoch_;
Use the setters, so you don't need to write the requirement checks twice

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
>      function _getPotionsLeft() private view returns (uint256 potionsLeft) {
Remove this function as it can be gamed if someone sends a potion to this contract directly and would make `_getPotionID` revert.

2022-11-24 17:52 UTC, 0x0Louis commented on src/Apothecary.sol
> +        }
Cache and use `_potionsOwnedByContract.length` instead

2022-11-24 17:53 UTC, 0x0Louis commented on src/Apothecary.sol
>      }
It shouldn't set the current epoch either 🤔

2022-11-25 08:56 UTC, Mathieu-Be commented on src/Apothecary.sol
>      }
True but I prefer to have flexibility here and don't over complicate things. We can enforce this on our side (and we probably won't call this function ever)

2022-11-25 09:00 UTC, Mathieu-Be commented on src/Apothecary.sol
>      }
Added a test to ensure `makePotions` still works after weird difficulties updates tho

2022-11-26 03:34 UTC, 0x0Louis requested changes

2022-11-26 03:34 UTC, 0x0Louis commented on src/Apothecary.sol
> +        totalBrewsCount += doctorIDsLength / 5;
This should probably be `totalBrewsCount += doctorIDsLength;`, because right now `totalPotionsBrewed` could be greater than `totalBrewsCount`, which would be weird

2022-11-26 03:35 UTC, 0x0Louis commented on src/Apothecary.sol
>      }
Sounds good

2022-11-28 08:34 UTC, Mathieu-Be commented on src/Apothecary.sol
> +        totalBrewsCount += doctorIDsLength / 5;
Success rate will be 2% at most so that's very unlikely. I prefer to keep the count grouped by 5 doctors, it would be divided on the front-end anyways if I was doing `totalBrewsCount += doctorIDsLength;`.

2022-11-28 11:10 UTC, 0x0Louis approved these changes

2022-11-28 13:30 UTC, merged